### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by szczuru** [Rinnegatamante/goo_vita#1]
Hi, i can't change language of the game via config file. WoG have polish translation and few other languages stored in text.xml.mp3 (which is txt file). On Pc i could change language by changing line in config.txt.mp3 file:

`	<param name="language" value="{LANG}"/>`

and change {LANG} variable to "pl". But after changing that game is still in english - i checked config file once more and still language is set to "pl".

**Comment by Rinnegatamante** [comment]
Current port forces default language so you'd have to replace all english text with polish one. I can add other languages support in next releases however.

**Comment by szczuru** [comment]
File with all text looks something like this (i'm writing from memory). 

```
TextId:xx
Text=default=text_in_english
Text=es=text_in_spanish
Text=pl=text_in_polish
Text=de=text_in_german
Text=it=text_in_italian
```

So i repleced all "Text=default=" with "Text=pl=" (and vice versa) but after that game won't start with C2-12828-2 error. 
So i'm looking forward for next release of this port.

**Comment by Rinnegatamante** [comment]
Available in v.1.1 https://github.com/Rinnegatamante/goo_vita/releases/tag/v.1.1
